export enum ErrorCode {
    USER_UNDEFINED = 'USER_UNDEFINED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_TYPE_INVALID = 'USER_TYPE_INVALID',
    USER_STATUS_INVALID = 'USER_STATUS_INVALID',
    USER_LEDGER_NOT_FOUND = 'USER_LEDGER_NOT_FOUND',
    USER_UID_ALREADY_EXISTS = 'USER_UID_ALREADY_EXISTS',

    LOGIN_ID_INVALID = 'LOGIN_ID_INVALID',
    LOGIN_TOKEN_INVALID = 'LOGIN_TOKEN_INVALID',
    LOGIN_TOKEN_EXPIRED = 'LOGIN_TOKEN_EXPIRED',
    LOGIN_SIGNATURE_INVALID = 'LOGIN_SIGNATURE_INVALID',

    BILL_UNDEFINED = 'BILL_UNDEFINED',
    BILL_NOT_FOUND = 'BILL_NOT_FOUND',
    BILL_FORBIDDEN = 'BILL_FORBIDDEN',
    
    TERMINAL_UNDEFINED = 'TERMINAL_UNDEFINED',
    TERMINAL_NOT_FOUND = 'TERMINAL_NOT_FOUND',
    TERMINAL_FORBIDDEN = 'TERMINAL_FORBIDDEN',

    COMPANY_UNDEFINED = 'COMPANY_UNDEFINED',
    COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
    COMPANY_STATUS_INVALID = 'COMPANY_STATUS_INVALID',
    COMPANY_NOT_UNDEFINED = 'COMPANY_NOT_UNDEFINED',
    COMPANY_ROLE_UNDEFINED = 'COMPANY_ROLE_UNDEFINED',
    COMPANY_ROLE_INVALID = 'COMPANY_ROLE_INVALID',
    COMPANY_LEDGER_NOT_FOUND = 'COMPANY_LEDGER_NOT_FOUND',

    COIN_UNDEFINED = 'COIN_UNDEFINED',
    COIN_NOT_FOUND = 'COIN_NOT_FOUND',
    COIN_BALANCE_NOT_FOUND = 'COIN_BALANCE_NOT_FOUND',
    COIN_BALANCE_INSUFFICIENT = 'COIN_BALANCE_INSUFFICIENT',

    INVALID_REQUEST = 'INVALID_REQUEST',
    HEADER_UNDEFINED = 'HEADER_UNDEFINED',
    SIGNATURE_INVALID = 'SIGNATURE_INVALID',
}
